export interface CanonicalCountry {
    code: string;
    name: string;
}

// Danh sách alias xử lý các cách ghi quốc gia thường gặp trong thông số sản phẩm tiếng Việt của Tiki.
export const COUNTRY_ALIASES: Readonly<Record<string, CanonicalCountry>> = {
    'viet nam': { code: 'VN', name: 'Việt Nam' },
    vietnam: { code: 'VN', name: 'Việt Nam' },
    my: { code: 'US', name: 'Hoa Kỳ' },
    'hoa ky': { code: 'US', name: 'Hoa Kỳ' },
    usa: { code: 'US', name: 'Hoa Kỳ' },
    'united states': { code: 'US', name: 'Hoa Kỳ' },
    'trung quoc': { code: 'CN', name: 'Trung Quốc' },
    china: { code: 'CN', name: 'Trung Quốc' },
    'nhat ban': { code: 'JP', name: 'Nhật Bản' },
    japan: { code: 'JP', name: 'Nhật Bản' },
    'han quoc': { code: 'KR', name: 'Hàn Quốc' },
    korea: { code: 'KR', name: 'Hàn Quốc' },
    'south korea': { code: 'KR', name: 'Hàn Quốc' },
    duc: { code: 'DE', name: 'Đức' },
    germany: { code: 'DE', name: 'Đức' },
    phap: { code: 'FR', name: 'Pháp' },
    france: { code: 'FR', name: 'Pháp' },
    anh: { code: 'GB', name: 'Vương quốc Anh' },
    uk: { code: 'GB', name: 'Vương quốc Anh' },
    'united kingdom': { code: 'GB', name: 'Vương quốc Anh' },
    y: { code: 'IT', name: 'Ý' },
    italy: { code: 'IT', name: 'Ý' },
    'tay ban nha': { code: 'ES', name: 'Tây Ban Nha' },
    spain: { code: 'ES', name: 'Tây Ban Nha' },
    'thuy si': { code: 'CH', name: 'Thụy Sĩ' },
    switzerland: { code: 'CH', name: 'Thụy Sĩ' },
    'thuy dien': { code: 'SE', name: 'Thụy Điển' },
    sweden: { code: 'SE', name: 'Thụy Điển' },
    'dan mach': { code: 'DK', name: 'Đan Mạch' },
    denmark: { code: 'DK', name: 'Đan Mạch' },
    'ha lan': { code: 'NL', name: 'Hà Lan' },
    netherlands: { code: 'NL', name: 'Hà Lan' },
    bi: { code: 'BE', name: 'Bỉ' },
    belgium: { code: 'BE', name: 'Bỉ' },
    uc: { code: 'AU', name: 'Úc' },
    australia: { code: 'AU', name: 'Úc' },
    'new zealand': { code: 'NZ', name: 'New Zealand' },
    canada: { code: 'CA', name: 'Canada' },
    singapore: { code: 'SG', name: 'Singapore' },
    'thai lan': { code: 'TH', name: 'Thái Lan' },
    thailand: { code: 'TH', name: 'Thái Lan' },
    malaysia: { code: 'MY', name: 'Malaysia' },
    indonesia: { code: 'ID', name: 'Indonesia' },
    'an do': { code: 'IN', name: 'Ấn Độ' },
    india: { code: 'IN', name: 'Ấn Độ' },
    'dai loan': { code: 'TW', name: 'Đài Loan' },
    taiwan: { code: 'TW', name: 'Đài Loan' },
    'hong kong': { code: 'HK', name: 'Hồng Kông' },
    brazil: { code: 'BR', name: 'Brazil' },
    mexico: { code: 'MX', name: 'Mexico' },
    nga: { code: 'RU', name: 'Nga' },
    russia: { code: 'RU', name: 'Nga' },
    'ba lan': { code: 'PL', name: 'Ba Lan' },
    poland: { code: 'PL', name: 'Ba Lan' },
    'phan lan': { code: 'FI', name: 'Phần Lan' },
    finland: { code: 'FI', name: 'Phần Lan' },
    'na uy': { code: 'NO', name: 'Na Uy' },
    norway: { code: 'NO', name: 'Na Uy' },
    ao: { code: 'AT', name: 'Áo' },
    austria: { code: 'AT', name: 'Áo' },
    'cong hoa sec': { code: 'CZ', name: 'Cộng hòa Séc' },
    czechia: { code: 'CZ', name: 'Cộng hòa Séc' },
    hungary: { code: 'HU', name: 'Hungary' },
    'tho nhi ky': { code: 'TR', name: 'Thổ Nhĩ Kỳ' },
    turkey: { code: 'TR', name: 'Thổ Nhĩ Kỳ' },
    israel: { code: 'IL', name: 'Israel' },
};
